# Generated by Django 5.1.4 on 2025-02-01 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_propertyimage_delete_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='actual_price',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='predicted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
