# Generated by Django 5.1.4 on 2025-02-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_property_actual_price_property_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
