# Generated by Django 5.1.4 on 2025-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_listed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
