# Generated by Django 5.1.4 on 2025-02-05 16:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_property_images_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
