# Generated by Django 5.1.4 on 2025-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_property_images_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
    ]
