# Generated by Django 5.1.4 on 2025-02-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_bid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='predicted_price',
        ),
    ]
