# Generated by Django 5.1.4 on 2025-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_property_predicted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
