# Generated by Django 5.1.4 on 2025-02-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_bid_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-created_at']},
        ),
    ]
